# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: SLSA container generator

# This workflow builds the opencode and claude-code images, generates SLSA
# provenance for them, and pushes the images and provenance to the container
# registry.

# NOTE: Image tags are based on the package version, so image tags will not
#       be immutable and will be updated with each merge to main.

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  # NOTE: We don't use a matrix strategy here because we need the outputs of
  #       each build job.

  # This step builds our image, pushes it, and outputs the repo hash digest.
  build-opencode:
    name: Build opencode image
    permissions:
      contents: read # for checking out the repo.
      packages: write # for pushing the image to the registry.
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          # NOTE: Do not use the cached binary for buildx to avoid potential
          # cache poisoning.
          cache-binary: false

      - name: Authenticate Docker
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: package
        run: |
          cd opencode
          package_version=$(npm list --depth=0 --json | jq -r '.dependencies."opencode-ai".required')
          echo "version=${package_version}" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/opencode
          tags: |
            type=raw,value=${{ steps.package.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          path: opencode/Dockerfile
          context: opencode/

      - name: Output image
        id: image
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          # NOTE: Set the image as an output because the `env` context is not
          # available to the inputs of a reusable workflow call.
          echo "image=${IMAGE_REGISTRY}/${REPO_OWNER}/opencode" >> "$GITHUB_OUTPUT"

  # This step calls the container workflow to generate provenance and push it to
  # the container registry.
  provenance-opencode:
    name: Generate SLSA provenance for opencode
    needs: [build-opencode]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.build-opencode.outputs.image }}
      digest: ${{ needs.build-opencode.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  # This step builds our image, pushes it, and outputs the repo hash digest.
  build-claude-code:
    name: Build claude-code image
    permissions:
      contents: read # for checking out the repo.
      packages: write # for pushing the image to the registry.
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          # NOTE: Do not use the cached binary for buildx to avoid potential
          # cache poisoning.
          cache-binary: false

      - name: Authenticate Docker
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: package
        run: |
          cd claude-code
          package_version=$(npm list --depth=1 --json | jq -r '.dependencies."@anthropic-ai/claude-code".required')
          echo "version=${package_version}" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/claude-code
          tags: |
            type=raw,value=${{ steps.package.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          path: claude-code/Dockerfile
          context: claude-code/

      - name: Output image
        id: image
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          # NOTE: Set the image as an output because the `env` context is not
          # available to the inputs of a reusable workflow call.
          echo "image=${IMAGE_REGISTRY}/${REPO_OWNER}/claude-code" >> "$GITHUB_OUTPUT"

  # This step calls the container workflow to generate provenance and push it to
  # the container registry.
  provenance-claude-code:
    name: Generate SLSA provenance for claude-code
    needs: [build-claude-code]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.build-claude-code.outputs.image }}
      digest: ${{ needs.build-claude-code.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
